version: "2.1"

services:
  personal-site:
    container_name: personal-site
    image: personal-site
    restart: always
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    logging:
      options:
        max-size: 50m
